/* Copyright 2025 The xLLM Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://gitcode.com/xLLM-AI/xllm_ops/blob/main/LICENSE

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

// Per-build arch selection (generated by CMake). On A5 this defines
// CATLASS_ARCH=3510 so the arch35 (A5) host tiling struct/branch is compiled in;
// on A3 it is empty. Included here so EVERY translation unit that pulls in this
// header (tiling.cpp, proto.cpp, ...) sees a consistent XAttentionTilingData
// layout, avoiding ODR violations.
#include "xa_arch_config.h"
#include "register/tilingdata_base.h"
#include "tiling/tiling_api.h"

namespace optiling {

#if defined(CATLASS_ARCH) && (CATLASS_ARCH == 3510)
// ===== A5(Ascend950/DAV_3510): nested tiling data =====
BEGIN_TILING_DATA_DEF(XABaseInfoTilingData)
  TILING_DATA_FIELD_DEF(int32_t, batchSize);
  TILING_DATA_FIELD_DEF(int32_t, beamSize);
  TILING_DATA_FIELD_DEF(int32_t, qHeads);
  TILING_DATA_FIELD_DEF(int32_t, kvHeads);
  TILING_DATA_FIELD_DEF(int32_t, groupSize);
  TILING_DATA_FIELD_DEF(int32_t, headDim);
  TILING_DATA_FIELD_DEF(float, scaleValue);
  TILING_DATA_FIELD_DEF(int32_t, totalTokensQ);
  TILING_DATA_FIELD_DEF(int32_t, sharedKvTokens);
  TILING_DATA_FIELD_DEF(int32_t, maxDecodeStep);
END_TILING_DATA_DEF;
REGISTER_TILING_DATA_CLASS(XABaseInfoTilingDataOp, XABaseInfoTilingData)

BEGIN_TILING_DATA_DEF(XASharedTilingData)
  TILING_DATA_FIELD_DEF(int32_t, totalTaskNum);
  TILING_DATA_FIELD_DEF(int32_t, perBatchHeadTaskNum);
  TILING_DATA_FIELD_DEF(int32_t, perCoreTaskNum);
  TILING_DATA_FIELD_DEF(int32_t, usedCoreNum);
END_TILING_DATA_DEF;
REGISTER_TILING_DATA_CLASS(XASharedTilingDataOp, XASharedTilingData)

BEGIN_TILING_DATA_DEF(XAUnsharedTilingData)
  TILING_DATA_FIELD_DEF(int32_t, kvBatchStride);
  TILING_DATA_FIELD_DEF(int32_t, groupCountPerLoop);
  TILING_DATA_FIELD_DEF(int32_t, perBatchTaskNum);
  TILING_DATA_FIELD_DEF(int32_t, perCoreTaskNum);
  TILING_DATA_FIELD_DEF(int32_t, totalTaskNum);
  TILING_DATA_FIELD_DEF(int32_t, usedCoreNum);
END_TILING_DATA_DEF;
REGISTER_TILING_DATA_CLASS(XAUnsharedTilingDataOp, XAUnsharedTilingData)

BEGIN_TILING_DATA_DEF(XACombineTilingData)
  TILING_DATA_FIELD_DEF(int32_t, rowPerLoop);
  TILING_DATA_FIELD_DEF(int32_t, rowNum);
  TILING_DATA_FIELD_DEF(int32_t, totalTaskNum);
  TILING_DATA_FIELD_DEF(int32_t, formerCoreNum);
  TILING_DATA_FIELD_DEF(int32_t, formerTaskNum);
  TILING_DATA_FIELD_DEF(int32_t, tailTaskNum);
  TILING_DATA_FIELD_DEF(int32_t, usedCoreNum);
END_TILING_DATA_DEF;
REGISTER_TILING_DATA_CLASS(XACombineTilingDataOp, XACombineTilingData)

BEGIN_TILING_DATA_DEF(XAttentionTilingData)
  TILING_DATA_FIELD_DEF(uint64_t, qOSize);
  TILING_DATA_FIELD_DEF(uint64_t, sumMaxSize);
  TILING_DATA_FIELD_DEF(uint64_t, sharedWorkspaceSize);
  TILING_DATA_FIELD_DEF_STRUCT(XABaseInfoTilingData, baseInfo);
  TILING_DATA_FIELD_DEF_STRUCT(XASharedTilingData, sharedInfo);
  TILING_DATA_FIELD_DEF_STRUCT(XAUnsharedTilingData, unsharedInfo);
  TILING_DATA_FIELD_DEF_STRUCT(XACombineTilingData, combineInfo);
END_TILING_DATA_DEF;

REGISTER_TILING_DATA_CLASS(XAttention, XAttentionTilingData)
#else
// ===== A3(AtlasA2/A3): flat tiling data =====
BEGIN_TILING_DATA_DEF(XAttentionTilingData)
  TILING_DATA_FIELD_DEF(uint32_t, numHeads);
  TILING_DATA_FIELD_DEF(uint32_t, kvHeads);
  TILING_DATA_FIELD_DEF(uint32_t, embeddingSize);
  TILING_DATA_FIELD_DEF(uint32_t, batch);
  TILING_DATA_FIELD_DEF(uint32_t, beamSize);
  TILING_DATA_FIELD_DEF(float, scaleValue);
  TILING_DATA_FIELD_DEF(uint32_t, maskType);
  TILING_DATA_FIELD_DEF(uint32_t, numTokens);
  TILING_DATA_FIELD_DEF(uint32_t, numBlocks);
  TILING_DATA_FIELD_DEF(uint32_t, blockSize);
  TILING_DATA_FIELD_DEF(uint32_t, sharedCoreNum);
  TILING_DATA_FIELD_DEF(uint32_t, maxNumBlocksPerBatch);
  TILING_DATA_FIELD_DEF(uint32_t, firstSharedBatchTaskNum);
  TILING_DATA_FIELD_DEF(uint32_t, sharedTotalTaskNum);
  TILING_DATA_FIELD_DEF(uint64_t, mm1OutSize);
  TILING_DATA_FIELD_DEF(uint64_t, smOnlineOutSize);
  TILING_DATA_FIELD_DEF(uint64_t, mm2OutSize);
  TILING_DATA_FIELD_DEF(uint64_t, updateSize);
  TILING_DATA_FIELD_DEF(uint32_t, rowSumMaxSize);
  TILING_DATA_FIELD_DEF(uint64_t, sharedWorkspaceSize);
  TILING_DATA_FIELD_DEF(uint32_t, groupSize);
  TILING_DATA_FIELD_DEF(uint32_t, maxDecodeStep);
  TILING_DATA_FIELD_DEF(uint32_t, unsharedCoreNum);
  TILING_DATA_FIELD_DEF(uint32_t, unshareGroupCountPerLoop);
  TILING_DATA_FIELD_DEF(uint32_t, unsharedFullCoreNum);
  TILING_DATA_FIELD_DEF(uint32_t, unsharedTaskNumHead);
  TILING_DATA_FIELD_DEF(uint32_t, unsharedTaskNumTail);
  TILING_DATA_FIELD_DEF(uint32_t, unsharedLoopCountPerBatch);
  TILING_DATA_FIELD_DEF(uint32_t, combineFormerCoreNum);
  TILING_DATA_FIELD_DEF(uint32_t, combineFormerRowNum);
  TILING_DATA_FIELD_DEF(uint32_t, combineTailRowNum);
  TILING_DATA_FIELD_DEF(uint32_t, combineCoreNum);
END_TILING_DATA_DEF;

REGISTER_TILING_DATA_CLASS(XAttention, XAttentionTilingData)
#endif

}
