// -----------------------------------------------------------------------------------------------------------
// Copyright (c) 2025 Huawei Technologies Co., Ltd.
// This file is generated by CMake (configure_file) from xa_arch_config.h.in.
// DO NOT EDIT the generated header directly.
//
// Purpose: The host tiling.cpp is compiled into a framework-aggregated OBJECT
// library (ophost_xllm_tiling_obj) defined in another directory, so per-source
// COMPILE_DEFINITIONS / add_compile_definitions from this op subdir cannot reach
// it. Instead we bake the A5 (arch35) selection into a generated header that the
// tiling sources include. The value is decided at CMake configure time based on
// ASCEND_COMPUTE_UNIT / SOC_VERSION, so A3 and A5 builds get different content.
// -----------------------------------------------------------------------------------------------------------
#ifndef XA_ARCH_CONFIG_H
#define XA_ARCH_CONFIG_H

// #define CATLASS_ARCH 3510 is replaced by CMake:
//   - on A5 (ascend950 / ascend310p5): "#define CATLASS_ARCH 3510"
//   - otherwise                      : (empty)
#define CATLASS_ARCH 3510

#endif  // XA_ARCH_CONFIG_H
